### PR TITLE
Add first version of bulk and filepaths files for data loading

### PR DESCRIPTION
**Pull request by sbesson**
At the moment this imports all the TIFF and ICS/IDS files uploaded as part of the submissions into datastets, one per assay.

More refinement might be needed as the curation of this datasets progresses. In particular, we might want to handle the labelled TIFF masks similarly to what we did for `idr0052` i.e. attach them as file annotations to the raw images and convert them into ROIs.

/cc @manics @francesw

### CODE REVIEW

**Comment by sbesson** [comment]
Loaded into `test64` 

Screen Shot 2019-05-29 at 11 14 00

**Comment by manics** [comment]
Are experiments B-E still relevant?

**Comment by sbesson** [comment]
Given that everything is acquired with the same modalities, we discussed this with @francesw and decided to turn `experimentA-experimentE` into `experimentA` with 5 assays. The metadata and measurement files will need to be unified as well

**Comment by manics** [comment]
Apart from the mismatch in metadata (which could be fixed later) looks OK to me.

**Comment by sbesson** [comment]
@manics pushed another commit to move all original files under `experimentA`

**Comment by manics** [comment]
Shouldn't the files be concatenated with the corresponding `experimentA-*` files instead of copied?

**Comment by sbesson** [comment]
I defer to @francesw on what she prefers here. Previously we have kept the original assays files and done the concatenation in the `annotation.csv` i.e. our curated metadata file derived from the assays - e.g. https://github.com/IDR/idr0052-walther-condensinmap/tree/master/experimentC.

**Comment by francesw** [comment]
I've started working on the annotations.cvs.  Image files will be listed with Dataset Names, as 5 assays, as laid out on testing.

**Pull request merged**
